services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ata-api
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1

  # db:
  #   image: postgres:latest
  #   container_name: ata-db
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data/
  #     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: