services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ata-api
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
      - MODE=api
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data
      - ./ATA/student_data:/app/ATA/student_data

  console:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ata-console
    environment:
      - PYTHONUNBUFFERED=1
      - MODE=console
    stdin_open: true
    tty: true
    depends_on:
      - api
    volumes:
      - ./ATA:/app/ATA
      - ./data:/app/data
      - ./ATA/student_data:/app/ATA/student_data

  # db:
  #   image: postgres:latest
  #   container_name: ata-db
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data/
  #     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: